// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezknucluuyvhphhbsdga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6a251Y2x1dXl2aHBoaGJzZGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTQxNjcsImV4cCI6MjA2MTkzMDE2N30.JGT4tn0LpbqvXb5PS7H-3FSJAzZqVdL_Tw2AZ45Ojr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);